Lesson17
SergSmiian/Smiian.Serhii pull request #9
Opened 2022-08-06 11:34 UTC by SergSmiian

2022-08-06 11:35 UTC, SergSmiian commented
![](https://github.trello.services/images/mini-trello-icon.png) [IO/NIO](https://trello.com/c/vzEdHGPl/80-io-nio)

2022-08-06 22:26 UTC, Fabolo12 requested changes

2022-08-06 22:26 UTC, Fabolo12 commented on src/main/java/com/Main.java
> +        System.out.println (XML_PARSER.parse("src\\main\\resources\\lesson17.xml"));
Чтение с файла не верное

2022-08-06 22:26 UTC, Fabolo12 commented on src/main/java/com/model/vehicle/Auto.java
> +    public static class AutoBuilder{
А это же с дз про SOLID

2022-08-07 21:28 UTC, Fabolo12 approved these changes

2022-08-08 09:50 UTC, merged